-- Run this once in the Supabase SQL Editor for the Satona public chat.
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  username text not null check (char_length(btrim(username)) between 1 and 24),
  sender_id text not null check (char_length(sender_id) between 1 and 64),
  content text not null check (char_length(btrim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

drop policy if exists "Anyone can read chat messages" on public.chat_messages;
create policy "Anyone can read chat messages"
  on public.chat_messages for select to anon, authenticated using (true);

drop policy if exists "Anyone can send chat messages" on public.chat_messages;
create policy "Anyone can send chat messages"
  on public.chat_messages for insert to anon, authenticated with check (true);

grant select, insert on public.chat_messages to anon, authenticated;
grant usage, select on sequence public.chat_messages_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end
$$;
